export const GET_PROVINCE_ALL = "GET_PROVINCE_ALL";
export const GET_PROVINCE_ALL_SUCCESS = "GET_PROVINCE_ALL_SUCCESS";
export const GET_PROVINCE_ALL_FAIL = "GET_PROVINCE_ALL_FAIL";

export const GET_PROVINCE_ID = "GET_PROVINCE_ID";
export const GET_PROVINCE_ID_SUCCESS = "GET_PROVINCE_ID_SUCCESS";
export const GET_PROVINCE_ID_FAIL = "GET_PROVINCE_ID_FAIL";

export const GET_PROVINCE_BY_NATION_ID = "GET_PROVINCE_BY_NATION_ID";
export const GET_PROVINCE_BY_NATION_ID_SUCCESS = "GET_PROVINCE_BY_NATION_ID_SUCCESS";
export const GET_PROVINCE_BY_NATION_ID_FAIL = "GET_PROVINCE_BY_NATION_ID_FAIL";

export const SET_PROVINCE = "SET_PROVINCE";
export const SET_PROVINCE_SUCCESS = "SET_PROVINCE_SUCCESS";
export const SET_PROVINCE_FAIL = "SET_PROVINCE_FAIL";

export const UPDATE_PROVINCE = "UPDATE_PROVINCE";
export const UPDATE_PROVINCE_SUCCESS = "UPDATE_PROVINCE_SUCCESS";
export const UPDATE_PROVINCE_FAIL = "UPDATE_PROVINCE_FAIL";

export const DELETE_PROVINCE = "DELETE_PROVINCE";
export const DELETE_PROVINCE_SUCCESS = "DELETE_PROVINCE_SUCCESS";
export const DELETE_PROVINCE_FAIL = "DELETE_PROVINCE_FAIL";