export const GET_STATUSDETAIL_ALL = "GET_STATUSDETAIL_ALL";
export const GET_STATUSDETAIL_ALL_SUCCESS = "GET_STATUSDETAIL_ALL_SUCCESS";
export const GET_STATUSDETAIL_ALL_FAIL = "GET_STATUSDETAIL_ALL_FAIL";

export const GET_STATUSDETAIL_ID = "GET_STATUSDETAIL_ID";
export const GET_STATUSDETAIL_ID_SUCCESS = "GET_STATUSDETAIL_ID_SUCCESS";
export const GET_STATUSDETAIL_ID_FAIL = "GET_STATUSDETAIL_ID_FAIL";

export const SET_STATUSDETAIL = "SET_STATUSDETAIL";
export const SET_STATUSDETAIL_SUCCESS = "SET_STATUSDETAIL_SUCCESS";
export const SET_STATUSDETAIL_FAIL = "SET_STATUSDETAIL_FAIL";

export const UPDATE_STATUSDETAIL = "UPDATE_STATUSDETAIL";
export const UPDATE_STATUSDETAIL_SUCCESS = "UPDATE_STATUSDETAIL_SUCCESS";
export const UPDATE_STATUSDETAIL_FAIL = "UPDATE_STATUSDETAIL_FAIL";

export const DELETE_STATUSDETAIL = "DELETE_STATUSDETAIL";
export const DELETE_STATUSDETAIL_SUCCESS = "DELETE_STATUSDETAIL_SUCCESS";
export const DELETE_STATUSDETAIL_FAIL = "DELETE_STATUSDETAIL_FAIL";