export const GET_USERS_USER_ID_AND_TYPE = "GET_USERS_USER_ID_AND_TYPE";
export const GET_USERS_USER_ID_AND_TYPE_SUCCESS = "GET_USERS_USER_ID_AND_TYPE_SUCCESS";
export const GET_USERS_USER_ID_AND_TYPE_FAIL = "GET_USERS_USER_ID_AND_TYPE_FAIL";

export const GET_USERS_ALL = "GET_USERS_ALL";
export const GET_USERS_ALL_SUCCESS = "GET_USERS_ALL_SUCCESS";
export const GET_USERS_ALL_FAIL = "GET_USERS_ALL_FAIL";

export const GET_USERS_LOGIN = "GET_USERS_LOGIN";
export const GET_USERS_LOGIN_SUCCESS = "GET_USERS_LOGIN_SUCCESS";
export const GET_USERS_LOGIN_FAIL = "GET_USERS_LOGIN_FAIL";

export const GET_USERS_ID = "GET_USERS_ID";
export const GET_USERS_ID_SUCCESS = "GET_USERS_ID_SUCCESS";
export const GET_USERS_ID_FAIL = "GET_USERS_ID_FAIL";

export const SET_USERS = "SET_USERS";
export const SET_USERS_SUCCESS = "SET_USERS_SUCCESS";
export const SET_USERS_FAIL = "SET_USERS_FAIL";

export const UPDATE_USERS = "UPDATE_USERS";
export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS";
export const UPDATE_USERS_FAIL = "UPDATE_USERS_FAIL";

export const DELETE_USERS = "DELETE_USERS";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const DELETE_USERS_FAIL = "DELETE_USERS_FAIL";