export const GET_ALIENREGISTRATIONCARD_ALL = "GET_ALIENREGISTRATIONCARD_ALL";
export const GET_ALIENREGISTRATIONCARD_ALL_SUCCESS = "GET_ALIENREGISTRATIONCARD_ALL_SUCCESS";
export const GET_ALIENREGISTRATIONCARD_ALL_FAIL = "GET_ALIENREGISTRATIONCARD_ALL_FAIL";

export const GET_ALIENREGISTRATIONCARD_ALLINFO = "GET_ALIENREGISTRATIONCARD_ALLINFO";
export const GET_ALIENREGISTRATIONCARD_ALLINFO_SUCCESS = "GET_ALIENREGISTRATIONCARD_ALLINFO_SUCCESS";
export const GET_ALIENREGISTRATIONCARD_ALLINFO_FAIL = "GET_ALIENREGISTRATIONCARD_ALLINFO_FAIL";

export const GET_ALIENREGISTRATIONCARD_ID = "GET_ALIENREGISTRATIONCARD_ID";
export const GET_ALIENREGISTRATIONCARD_ID_SUCCESS = "GET_ALIENREGISTRATIONCARD_ID_SUCCESS";
export const GET_ALIENREGISTRATIONCARD_ID_FAIL = "GET_ALIENREGISTRATIONCARD_ID_FAIL";

export const SET_ALIENREGISTRATIONCARD = "SET_ALIENREGISTRATIONCARD";
export const SET_ALIENREGISTRATIONCARD_SUCCESS = "SET_ALIENREGISTRATIONCARD_SUCCESS";
export const SET_ALIENREGISTRATIONCARD_FAIL = "SET_ALIENREGISTRATIONCARD_FAIL";

export const UPDATE_ALIENREGISTRATIONCARD = "UPDATE_ALIENREGISTRATIONCARD";
export const UPDATE_ALIENREGISTRATIONCARD_SUCCESS = "UPDATE_ALIENREGISTRATIONCARD_SUCCESS";
export const UPDATE_ALIENREGISTRATIONCARD_FAIL = "UPDATE_ALIENREGISTRATIONCARD_FAIL";

export const DELETE_ALIENREGISTRATIONCARD = "DELETE_ALIENREGISTRATIONCARD";
export const DELETE_ALIENREGISTRATIONCARD_SUCCESS = "DELETE_ALIENREGISTRATIONCARD_SUCCESS";
export const DELETE_ALIENREGISTRATIONCARD_FAIL = "DELETE_ALIENREGISTRATIONCARD_FAIL";