export const GET_RECEIVINGFACTORY_ALL = "GET_RECEIVINGFACTORY_ALL";
export const GET_RECEIVINGFACTORY_ALL_SUCCESS = "GET_RECEIVINGFACTORY_ALL_SUCCESS";
export const GET_RECEIVINGFACTORY_ALL_FAIL = "GET_RECEIVINGFACTORY_ALL_FAIL";

export const GET_RECEIVINGFACTORY_ID = "GET_RECEIVINGFACTORY_ID";
export const GET_RECEIVINGFACTORY_ID_SUCCESS = "GET_RECEIVINGFACTORY_ID_SUCCESS";
export const GET_RECEIVINGFACTORY_ID_FAIL = "GET_RECEIVINGFACTORY_ID_FAIL";

export const SET_RECEIVINGFACTORY = "SET_RECEIVINGFACTORY";
export const SET_RECEIVINGFACTORY_SUCCESS = "SET_RECEIVINGFACTORY_SUCCESS";
export const SET_RECEIVINGFACTORY_FAIL = "SET_RECEIVINGFACTORY_FAIL";

export const UPDATE_RECEIVINGFACTORY = "UPDATE_RECEIVINGFACTORY";
export const UPDATE_RECEIVINGFACTORY_SUCCESS = "UPDATE_RECEIVINGFACTORY_SUCCESS";
export const UPDATE_RECEIVINGFACTORY_FAIL = "UPDATE_RECEIVINGFACTORY_FAIL";

export const DELETE_RECEIVINGFACTORY = "DELETE_RECEIVINGFACTORY";
export const DELETE_RECEIVINGFACTORY_SUCCESS = "DELETE_RECEIVINGFACTORY_SUCCESS";
export const DELETE_RECEIVINGFACTORY_FAIL = "DELETE_RECEIVINGFACTORY_FAIL";