export const GET_TICKET_ALL = "GET_TICKET_ALL";
export const GET_TICKET_ALL_SUCCESS = "GET_TICKET_ALL_SUCCESS";
export const GET_TICKET_ALL_FAIL = "GET_TICKET_ALL_FAIL";

export const GET_TICKET_ALLINFO = "GET_TICKET_ALLINFO";
export const GET_TICKET_ALLINFO_SUCCESS = "GET_TICKET_ALLINFO_SUCCESS";
export const GET_TICKET_ALLINFO_FAIL = "GET_TICKET_ALLINFO_FAIL";

export const GET_TICKET_ID = "GET_TICKET_ID";
export const GET_TICKET_ID_SUCCESS = "GET_TICKET_ID_SUCCESS";
export const GET_TICKET_ID_FAIL = "GET_TICKET_ID_FAIL";

export const SET_TICKET = "SET_TICKET";
export const SET_TICKET_SUCCESS = "SET_TICKET_SUCCESS";
export const SET_TICKET_FAIL = "SET_TICKET_FAIL";

export const UPDATE_TICKET = "UPDATE_TICKET";
export const UPDATE_TICKET_SUCCESS = "UPDATE_TICKET_SUCCESS";
export const UPDATE_TICKET_FAIL = "UPDATE_TICKET_FAIL";

export const DELETE_TICKET = "DELETE_TICKET";
export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS";
export const DELETE_TICKET_FAIL = "DELETE_TICKET_FAIL";