export const GET_STATUSOFRESIDENCE_ALL = "GET_STATUSOFRESIDENCE_ALL";
export const GET_STATUSOFRESIDENCE_ALL_SUCCESS = "GET_STATUSOFRESIDENCE_ALL_SUCCESS";
export const GET_STATUSOFRESIDENCE_ALL_FAIL = "GET_STATUSOFRESIDENCE_ALL_FAIL";

export const GET_STATUSOFRESIDENCE_ID = "GET_STATUSOFRESIDENCE_ID";
export const GET_STATUSOFRESIDENCE_ID_SUCCESS = "GET_STATUSOFRESIDENCE_ID_SUCCESS";
export const GET_STATUSOFRESIDENCE_ID_FAIL = "GET_STATUSOFRESIDENCE_ID_FAIL";

export const SET_STATUSOFRESIDENCE = "SET_STATUSOFRESIDENCE";
export const SET_STATUSOFRESIDENCE_SUCCESS = "SET_STATUSOFRESIDENCE_SUCCESS";
export const SET_STATUSOFRESIDENCE_FAIL = "SET_STATUSOFRESIDENCE_FAIL";

export const UPDATE_STATUSOFRESIDENCE = "UPDATE_STATUSOFRESIDENCE";
export const UPDATE_STATUSOFRESIDENCE_SUCCESS = "UPDATE_STATUSOFRESIDENCE_SUCCESS";
export const UPDATE_STATUSOFRESIDENCE_FAIL = "UPDATE_STATUSOFRESIDENCE_FAIL";

export const DELETE_STATUSOFRESIDENCE = "DELETE_STATUSOFRESIDENCE";
export const DELETE_STATUSOFRESIDENCE_SUCCESS = "DELETE_STATUSOFRESIDENCE_SUCCESS";
export const DELETE_STATUSOFRESIDENCE_FAIL = "DELETE_STATUSOFRESIDENCE_FAIL";