export const GET_NOTI_ALL = "GET_NOTI_ALL";
export const GET_NOTI_ALL_SUCCESS = "GET_NOTI_ALL_SUCCESS";
export const GET_NOTI_ALL_FAIL = "GET_NOTI_ALL_FAIL";

export const GET_NOTI_USERID = "GET_NOTI_USERID";
export const GET_NOTI_USERID_SUCCESS = "GET_NOTI_USERID_SUCCESS";
export const GET_NOTI_USERID_FAIL = "GET_NOTI_USERID_FAIL";

export const GET_NOTI_ID = "GET_NOTI_ID";
export const GET_NOTI_ID_SUCCESS = "GET_NOTI_ID_SUCCESS";
export const GET_NOTI_ID_FAIL = "GET_NOTI_ID_FAIL";

export const SET_NOTI = "SET_NOTI";
export const SET_NOTI_SUCCESS = "SET_NOTI_SUCCESS";
export const SET_NOTI_FAIL = "SET_NOTI_FAIL";

export const UPDATE_NOTI = "UPDATE_NOTI";
export const UPDATE_NOTI_SUCCESS = "UPDATE_NOTI_SUCCESS";
export const UPDATE_NOTI_FAIL = "UPDATE_NOTI_FAIL";

export const DELETE_NOTI = "DELETE_NOTI";
export const DELETE_NOTI_SUCCESS = "DELETE_NOTI_SUCCESS";
export const DELETE_NOTI_FAIL = "DELETE_NOTI_FAIL";