export const GET_TICKETDETAIL_ALL = "GET_TICKETDETAIL_ALL";
export const GET_TICKETDETAIL_ALL_SUCCESS = "GET_TICKETDETAIL_ALL_SUCCESS";
export const GET_TICKETDETAIL_ALL_FAIL = "GET_TICKETDETAIL_ALL_FAIL";

export const GET_TICKETDETAIL_ID = "GET_TICKETDETAIL_ID";
export const GET_TICKETDETAIL_ID_SUCCESS = "GET_TICKETDETAIL_ID_SUCCESS";
export const GET_TICKETDETAIL_ID_FAIL = "GET_TICKETDETAIL_ID_FAIL";

export const SET_TICKETDETAIL = "SET_TICKETDETAIL";
export const SET_TICKETDETAIL_SUCCESS = "SET_TICKETDETAIL_SUCCESS";
export const SET_TICKETDETAIL_FAIL = "SET_TICKETDETAIL_FAIL";

export const UPDATE_TICKETDETAIL = "UPDATE_TICKETDETAIL";
export const UPDATE_TICKETDETAIL_SUCCESS = "UPDATE_TICKETDETAIL_SUCCESS";
export const UPDATE_TICKETDETAIL_FAIL = "UPDATE_TICKETDETAIL_FAIL";

export const DELETE_TICKETDETAIL = "DELETE_TICKETDETAIL";
export const DELETE_TICKETDETAIL_SUCCESS = "DELETE_TICKETDETAIL_SUCCESS";
export const DELETE_TICKETDETAIL_FAIL = "DELETE_TICKETDETAIL_FAIL";