export const GET_EMPLOYEE_ALL = "GET_EMPLOYEE_ALL";
export const GET_EMPLOYEE_ALL_SUCCESS = "GET_EMPLOYEE_ALL_SUCCESS";
export const GET_EMPLOYEE_ALL_FAIL = "GET_EMPLOYEE_ALL_FAIL";

export const GET_EMPLOYEE_ID = "GET_EMPLOYEE_ID";
export const GET_EMPLOYEE_ID_SUCCESS = "GET_EMPLOYEE_ID_SUCCESS";
export const GET_EMPLOYEE_ID_FAIL = "GET_EMPLOYEE_ID_FAIL";

export const SET_EMPLOYEE = "SET_EMPLOYEE";
export const SET_EMPLOYEE_SUCCESS = "SET_EMPLOYEE_SUCCESS";
export const SET_EMPLOYEE_FAIL = "SET_EMPLOYEE_FAIL";

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAIL = "UPDATE_EMPLOYEE_FAIL";

export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAIL = "DELETE_EMPLOYEE_FAIL";