export const GET_KEYLICENSE_ALL = "GET_KEYLICENSE_ALL";
export const GET_KEYLICENSE_ALL_SUCCESS = "GET_KEYLICENSE_ALL_SUCCESS";
export const GET_KEYLICENSE_ALL_FAIL = "GET_KEYLICENSE_ALL_FAIL";

export const GET_KEYLICENSE_ID = "GET_KEYLICENSE_ID";
export const GET_KEYLICENSE_ID_SUCCESS = "GET_KEYLICENSE_ID_SUCCESS";
export const GET_KEYLICENSE_ID_FAIL = "GET_KEYLICENSE_ID_FAIL";

export const SET_KEYLICENSE = "SET_KEYLICENSE";
export const SET_KEYLICENSE_SUCCESS = "SET_KEYLICENSE_SUCCESS";
export const SET_KEYLICENSE_FAIL = "SET_KEYLICENSE_FAIL";

export const UPDATE_KEYLICENSE = "UPDATE_KEYLICENSE";
export const UPDATE_KEYLICENSE_SUCCESS = "UPDATE_KEYLICENSE_SUCCESS";
export const UPDATE_KEYLICENSE_FAIL = "UPDATE_KEYLICENSE_FAIL";

export const DELETE_KEYLICENSE = "DELETE_KEYLICENSE";
export const DELETE_KEYLICENSE_SUCCESS = "DELETE_KEYLICENSE_SUCCESS";
export const DELETE_KEYLICENSE_FAIL = "DELETE_KEYLICENSE_FAIL";