export const GET_DISPATCHINGCOMPANY_ALL = "GET_DISPATCHINGCOMPANY_ALL";
export const GET_DISPATCHINGCOMPANY_ALL_SUCCESS = "GET_DISPATCHINGCOMPANY_ALL_SUCCESS";
export const GET_DISPATCHINGCOMPANY_ALL_FAIL = "GET_DISPATCHINGCOMPANY_ALL_FAIL";

export const GET_DISPATCHINGCOMPANY_USERID = "GET_DISPATCHINGCOMPANY_USERID";
export const GET_DISPATCHINGCOMPANY_USERID_SUCCESS = "GET_DISPATCHINGCOMPANY_USERID_SUCCESS";
export const GET_DISPATCHINGCOMPANY_USERID_FAIL = "GET_DISPATCHINGCOMPANY_USERID_FAIL";

export const GET_DISPATCHINGCOMPANY_ID = "GET_DISPATCHINGCOMPANY_ID";
export const GET_DISPATCHINGCOMPANY_ID_SUCCESS = "GET_DISPATCHINGCOMPANY_ID_SUCCESS";
export const GET_DISPATCHINGCOMPANY_ID_FAIL = "GET_DISPATCHINGCOMPANY_ID_FAIL";

export const SET_DISPATCHINGCOMPANY = "SET_DISPATCHINGCOMPANY";
export const SET_DISPATCHINGCOMPANY_SUCCESS = "SET_DISPATCHINGCOMPANY_SUCCESS";
export const SET_DISPATCHINGCOMPANY_FAIL = "SET_DISPATCHINGCOMPANY_FAIL";

export const UPDATE_DISPATCHINGCOMPANY = "UPDATE_DISPATCHINGCOMPANY";
export const UPDATE_DISPATCHINGCOMPANY_SUCCESS = "UPDATE_DISPATCHINGCOMPANY_SUCCESS";
export const UPDATE_DISPATCHINGCOMPANY_FAIL = "UPDATE_DISPATCHINGCOMPANY_FAIL";

export const DELETE_DISPATCHINGCOMPANY = "DELETE_DISPATCHINGCOMPANY";
export const DELETE_DISPATCHINGCOMPANY_SUCCESS = "DELETE_DISPATCHINGCOMPANY_SUCCESS";
export const DELETE_DISPATCHINGCOMPANY_FAIL = "DELETE_DISPATCHINGCOMPANY_FAIL";