export const GET_DISTRICT_ALL = "GET_DISTRICT_ALL";
export const GET_DISTRICT_ALL_SUCCESS = "GET_DISTRICT_ALL_SUCCESS";
export const GET_DISTRICT_ALL_FAIL = "GET_DISTRICT_ALL_FAIL";

export const GET_DISTRICT_ID = "GET_DISTRICT_ID";
export const GET_DISTRICT_ID_SUCCESS = "GET_DISTRICT_ID_SUCCESS";
export const GET_DISTRICT_ID_FAIL = "GET_DISTRICT_ID_FAIL";

export const GET_DISTRICT_BY_PROVINCE_ID = "GET_DISTRICT_BY_PROVINCE_ID";
export const GET_DISTRICT_BY_PROVINCE_ID_SUCCESS = "GET_DISTRICT_BY_PROVINCE_ID_SUCCESS";
export const GET_DISTRICT_BY_PROVINCE_ID_FAIL = "GET_DISTRICT_BY_PROVINCE_ID_FAIL";

export const SET_DISTRICT = "SET_DISTRICT";
export const SET_DISTRICT_SUCCESS = "SET_DISTRICT_SUCCESS";
export const SET_DISTRICT_FAIL = "SET_DISTRICT_FAIL";

export const UPDATE_DISTRICT = "UPDATE_DISTRICT";
export const UPDATE_DISTRICT_SUCCESS = "UPDATE_DISTRICT_SUCCESS";
export const UPDATE_DISTRICT_FAIL = "UPDATE_DISTRICT_FAIL";

export const DELETE_DISTRICT = "DELETE_DISTRICT";
export const DELETE_DISTRICT_SUCCESS = "DELETE_DISTRICT_SUCCESS";
export const DELETE_DISTRICT_FAIL = "DELETE_DISTRICT_FAIL";