export const GET_NATION_ALL = "GET_NATION_ALL";
export const GET_NATION_ALL_SUCCESS = "GET_NATION_ALL_SUCCESS";
export const GET_NATION_ALL_FAIL = "GET_NATION_ALL_FAIL";

export const GET_NATION_ID = "GET_NATION_ID";
export const GET_NATION_ID_SUCCESS = "GET_NATION_ID_SUCCESS";
export const GET_NATION_ID_FAIL = "GET_NATION_ID_FAIL";

export const SET_NATION = "SET_NATION";
export const SET_NATION_SUCCESS = "SET_NATION_SUCCESS";
export const SET_NATION_FAIL = "SET_NATION_FAIL";

export const UPDATE_NATION = "UPDATE_NATION";
export const UPDATE_NATION_SUCCESS = "UPDATE_NATION_SUCCESS";
export const UPDATE_NATION_FAIL = "UPDATE_NATION_FAIL";

export const DELETE_NATION = "DELETE_NATION";
export const DELETE_NATION_SUCCESS = "DELETE_NATION_SUCCESS";
export const DELETE_NATION_FAIL = "DELETE_NATION_FAIL";