export const GET_ADDRESS_ALL = "GET_ADDRESS_ALL";
export const GET_ADDRESS_ALL_SUCCESS = "GET_ADDRESS_ALL_SUCCESS";
export const GET_ADDRESS_ALL_FAIL = "GET_ADDRESS_ALL_FAIL";

export const GET_ADDRESS_ID = "GET_ADDRESS_ID";
export const GET_ADDRESS_ID_SUCCESS = "GET_ADDRESS_ID_SUCCESS";
export const GET_ADDRESS_ID_FAIL = "GET_ADDRESS_ID_FAIL";

export const SET_ADDRESS = "SET_ADDRESS";
export const SET_ADDRESS_SUCCESS = "SET_ADDRESS_SUCCESS";
export const SET_ADDRESS_FAIL = "SET_ADDRESS_FAIL";

export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";

export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";