export const GET_STATUS_ALL = "GET_STATUS_ALL";
export const GET_STATUS_ALL_SUCCESS = "GET_STATUS_ALL_SUCCESS";
export const GET_STATUS_ALL_FAIL = "GET_STATUS_ALL_FAIL";

export const GET_STATUS_ID = "GET_STATUS_ID";
export const GET_STATUS_ID_SUCCESS = "GET_STATUS_ID_SUCCESS";
export const GET_STATUS_ID_FAIL = "GET_STATUS_ID_FAIL";

export const SET_STATUS = "SET_STATUS";
export const SET_STATUS_SUCCESS = "SET_STATUS_SUCCESS";
export const SET_STATUS_FAIL = "SET_STATUS_FAIL";

export const UPDATE_STATUS = "UPDATE_STATUS";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL";

export const DELETE_STATUS = "DELETE_STATUS";
export const DELETE_STATUS_SUCCESS = "DELETE_STATUS_SUCCESS";
export const DELETE_STATUS_FAIL = "DELETE_STATUS_FAIL";