export const GET_COMMUNE_ALL = "GET_COMMUNE_ALL";
export const GET_COMMUNE_ALL_SUCCESS = "GET_COMMUNE_ALL_SUCCESS";
export const GET_COMMUNE_ALL_FAIL = "GET_COMMUNE_ALL_FAIL";

export const GET_COMMUNE_ID = "GET_COMMUNE_ID";
export const GET_COMMUNE_ID_SUCCESS = "GET_COMMUNE_ID_SUCCESS";
export const GET_COMMUNE_ID_FAIL = "GET_COMMUNE_ID_FAIL";

export const GET_COMMUNE_BY_DISTRICT_ID = "GET_COMMUNE_BY_DISTRICT_ID";
export const GET_COMMUNE_BY_DISTRICT_ID_SUCCESS = "GET_COMMUNE_BY_DISTRICT_ID_SUCCESS";
export const GET_COMMUNE_BY_DISTRICT_ID_FAIL = "GET_COMMUNE_BY_DISTRICT_ID_FAIL";

export const SET_COMMUNE = "SET_COMMUNE";
export const SET_COMMUNE_SUCCESS = "SET_COMMUNE_SUCCESS";
export const SET_COMMUNE_FAIL = "SET_COMMUNE_FAIL";

export const UPDATE_COMMUNE = "UPDATE_COMMUNE";
export const UPDATE_COMMUNE_SUCCESS = "UPDATE_COMMUNE_SUCCESS";
export const UPDATE_COMMUNE_FAIL = "UPDATE_COMMUNE_FAIL";

export const DELETE_COMMUNE = "DELETE_COMMUNE";
export const DELETE_COMMUNE_SUCCESS = "DELETE_COMMUNE_SUCCESS";
export const DELETE_COMMUNE_FAIL = "DELETE_COMMUNE_FAIL";