
export const GET_INTERN_ALL = "GET_INTERN_ALL";
export const GET_INTERN_ALL_SUCCESS = "GET_INTERN_ALL_SUCCESS";
export const GET_INTERN_ALL_FAIL = "GET_INTERN_ALL_FAIL";

export const GET_INTERN_ALLINFO = "GET_INTERN_ALLINFO";
export const GET_INTERN_ALLINFO_SUCCESS = "GET_INTERN_ALLINFO_SUCCESS";
export const GET_INTERN_ALLINFO_FAIL = "GET_INTERN_ALLINFO_FAIL";

export const GET_INTERN_USERID = "GET_INTERN_USERID";
export const GET_INTERN_USERID_SUCCESS = "GET_INTERN_USERID_SUCCESS";
export const GET_INTERN_USERID_FAIL = "GET_INTERN_USERID_FAIL";

export const GET_INTERN_ID = "GET_INTERN_ID";
export const GET_INTERN_ID_SUCCESS = "GET_INTERN_ID_SUCCESS";
export const GET_INTERN_ID_FAIL = "GET_INTERN_ID_FAIL";

export const SET_INTERN = "SET_INTERN";
export const SET_INTERN_SUCCESS = "SET_INTERN_SUCCESS";
export const SET_INTERN_FAIL = "SET_INTERN_FAIL";

export const UPDATE_INTERN = "UPDATE_INTERN";
export const UPDATE_INTERN_SUCCESS = "UPDATE_INTERN_SUCCESS";
export const UPDATE_INTERN_FAIL = "UPDATE_INTERN_FAIL";

export const DELETE_INTERN = "DELETE_INTERN";
export const DELETE_INTERN_SUCCESS = "DELETE_INTERN_SUCCESS";
export const DELETE_INTERN_FAIL = "DELETE_INTERN_FAIL";

export const OPEN_MODAL = 'OPEN_MODAL'