export const GET_VIOLATETYPE_ALL = "GET_VIOLATETYPE_ALL";
export const GET_VIOLATETYPE_ALL_SUCCESS = "GET_VIOLATETYPE_ALL_SUCCESS";
export const GET_VIOLATETYPE_ALL_FAIL = "GET_VIOLATETYPE_ALL_FAIL";

export const GET_VIOLATETYPE_ID = "GET_VIOLATETYPE_ID";
export const GET_VIOLATETYPE_ID_SUCCESS = "GET_VIOLATETYPE_ID_SUCCESS";
export const GET_VIOLATETYPE_ID_FAIL = "GET_VIOLATETYPE_ID_FAIL";

export const SET_VIOLATETYPE = "SET_VIOLATETYPE";
export const SET_VIOLATETYPE_SUCCESS = "SET_VIOLATETYPE_SUCCESS";
export const SET_VIOLATETYPE_FAIL = "SET_VIOLATETYPE_FAIL";

export const UPDATE_VIOLATETYPE = "UPDATE_VIOLATETYPE";
export const UPDATE_VIOLATETYPE_SUCCESS = "UPDATE_VIOLATETYPE_SUCCESS";
export const UPDATE_VIOLATETYPE_FAIL = "UPDATE_VIOLATETYPE_FAIL";

export const DELETE_VIOLATETYPE = "DELETE_VIOLATETYPE";
export const DELETE_VIOLATETYPE_SUCCESS = "DELETE_VIOLATETYPE_SUCCESS";
export const DELETE_VIOLATETYPE_FAIL = "DELETE_VIOLATETYPE_FAIL";