export const GET_VIOLATELIST_ALL = "GET_VIOLATELIST_ALL";
export const GET_VIOLATELIST_ALL_SUCCESS = "GET_VIOLATELIST_ALL_SUCCESS";
export const GET_VIOLATELIST_ALL_FAIL = "GET_VIOLATELIST_ALL_FAIL";

export const GET_VIOLATELIST_ID = "GET_VIOLATELIST_ID";
export const GET_VIOLATELIST_ID_SUCCESS = "GET_VIOLATELIST_ID_SUCCESS";
export const GET_VIOLATELIST_ID_FAIL = "GET_VIOLATELIST_ID_FAIL";

export const SET_VIOLATELIST = "SET_VIOLATELIST";
export const SET_VIOLATELIST_SUCCESS = "SET_VIOLATELIST_SUCCESS";
export const SET_VIOLATELIST_FAIL = "SET_VIOLATELIST_FAIL";

export const UPDATE_VIOLATELIST = "UPDATE_VIOLATELIST";
export const UPDATE_VIOLATELIST_SUCCESS = "UPDATE_VIOLATELIST_SUCCESS";
export const UPDATE_VIOLATELIST_FAIL = "UPDATE_VIOLATELIST_FAIL";

export const DELETE_VIOLATELIST = "DELETE_VIOLATELIST";
export const DELETE_VIOLATELIST_SUCCESS = "DELETE_VIOLATELIST_SUCCESS";
export const DELETE_VIOLATELIST_FAIL = "DELETE_VIOLATELIST_FAIL";