export const GET_SYNDICATION_ALL = "GET_SYNDICATION_ALL";
export const GET_SYNDICATION_ALL_SUCCESS = "GET_SYNDICATION_ALL_SUCCESS";
export const GET_SYNDICATION_ALL_FAIL = "GET_SYNDICATION_ALL_FAIL";

export const GET_SYNDICATION_ID = "GET_SYNDICATION_ID";
export const GET_SYNDICATION_ID_SUCCESS = "GET_SYNDICATION_ID_SUCCESS";
export const GET_SYNDICATION_ID_FAIL = "GET_SYNDICATION_ID_FAIL";

export const SET_SYNDICATION = "SET_SYNDICATION";
export const SET_SYNDICATION_SUCCESS = "SET_SYNDICATION_SUCCESS";
export const SET_SYNDICATION_FAIL = "SET_SYNDICATION_FAIL";

export const UPDATE_SYNDICATION = "UPDATE_SYNDICATION";
export const UPDATE_SYNDICATION_SUCCESS = "UPDATE_SYNDICATION_SUCCESS";
export const UPDATE_SYNDICATION_FAIL = "UPDATE_SYNDICATION_FAIL";

export const DELETE_SYNDICATION = "DELETE_SYNDICATION";
export const DELETE_SYNDICATION_SUCCESS = "DELETE_SYNDICATION_SUCCESS";
export const DELETE_SYNDICATION_FAIL = "DELETE_SYNDICATION_FAIL";