export const GET_AVATA_ALL = "GET_AVATA_ALL";
export const GET_AVATA_ALL_SUCCESS = "GET_AVATA_ALL_SUCCESS";
export const GET_AVATA_ALL_FAIL = "GET_AVATA_ALL_FAIL";

export const GET_AVATA_ID = "GET_AVATA_ID";
export const GET_AVATA_ID_SUCCESS = "GET_AVATA_ID_SUCCESS";
export const GET_AVATA_ID_FAIL = "GET_AVATA_ID_FAIL";

export const SET_AVATA = "SET_AVATA";
export const SET_AVATA_SUCCESS = "SET_AVATA_SUCCESS";
export const SET_AVATA_FAIL = "SET_AVATA_FAIL";

export const UPDATE_AVATA = "UPDATE_AVATA";
export const UPDATE_AVATA_SUCCESS = "UPDATE_AVATA_SUCCESS";
export const UPDATE_AVATA_FAIL = "UPDATE_AVATA_FAIL";

export const DELETE_AVATA = "DELETE_AVATA";
export const DELETE_AVATA_SUCCESS = "DELETE_AVATA_SUCCESS";
export const DELETE_AVATA_FAIL = "DELETE_AVATA_FAIL";