export const GET_VIOLATE_ALL = "GET_VIOLATE_ALL";
export const GET_VIOLATE_ALL_SUCCESS = "GET_VIOLATE_ALL_SUCCESS";
export const GET_VIOLATE_ALL_FAIL = "GET_VIOLATE_ALL_FAIL";
export const GET_VIOLATE_USERID = "GET_VIOLATE_USERID";
export const GET_VIOLATE_USERID_SUCCESS = "GET_VIOLATE_USERID_SUCCESS";
export const GET_VIOLATE_USERID_FAIL = "GET_VIOLATE_USERID_FAIL";

export const GET_VIOLATE_ID = "GET_VIOLATE_ID";
export const GET_VIOLATE_ID_SUCCESS = "GET_VIOLATE_ID_SUCCESS";
export const GET_VIOLATE_ID_FAIL = "GET_VIOLATE_ID_FAIL";

export const SET_VIOLATE = "SET_VIOLATE";
export const SET_VIOLATE_SUCCESS = "SET_VIOLATE_SUCCESS";
export const SET_VIOLATE_FAIL = "SET_VIOLATE_FAIL";

export const UPDATE_VIOLATE = "UPDATE_VIOLATE";
export const UPDATE_VIOLATE_SUCCESS = "UPDATE_VIOLATE_SUCCESS";
export const UPDATE_VIOLATE_FAIL = "UPDATE_VIOLATE_FAIL";

export const DELETE_VIOLATE = "DELETE_VIOLATE";
export const DELETE_VIOLATE_SUCCESS = "DELETE_VIOLATE_SUCCESS";
export const DELETE_VIOLATE_FAIL = "DELETE_VIOLATE_FAIL";